USE db;

INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Oleg', 'Familiev', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Simonne','Singleterry', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Latia', 'Lheureux', true);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Digna', 'Derossett', true);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Shayna', 'Savage', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Eliana', 'Estrella', true);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Shauna', 'Sieg', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Marisha', 'Mccallie', true);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Shizuko', 'Savory', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Sheldon', 'Small', true);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Rebbeca', 'Ronning', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Oleg', 'Familiev', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Simonne','Singleterry', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Latia', 'Lheureux', true);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Digna', 'Derossett', true);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Shayna', 'Savage', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Eliana', 'Estrella', true);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Shauna', 'Sieg', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Marisha', 'Mccallie', true);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Shizuko', 'Savory', false);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Sheldon', 'Small', true);
INSERT INTO Persons (FirstName, LastName, CanDrive) VALUES ('Rebbeca', 'Ronning', false);
